# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  # The next three builders are `SharedPartBuilder` instances.
  # Notice they each have
  # `build_extensions` set to a `NAME.g.part` file.
  #    NAME corresponds to the second argument to the SharedPartBuilder ctor.
  #    `.g.part` is the extension expected of SharedPartBuilder.
  # `build_to: cache` - the output is not put directly into the project
  # `applies_builders` - uses the `combining_builder` from `source_gen` to
  #   combine the parts from each builder into one part file.
  mockito_builder:
    import: "package:mockito_builder/builder.dart"
    builder_factories: ["mockitoBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    runs_before: ["mockito|mockBuilder"]