name: mockito_builder
description: Generate Flutter `mockito` mocks and mock method with a list of types to be mocked.
version: 1.0.0
homepage: https://rmdy.be

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: '>=1.7.0 <4.0.0'
  source_gen: ^1.0.0
  build: ^2.0.0
  dart_style: '>=1.3.0 <3.0.0'
  code_builder: ^4.0.0
  #TODO change to ^1.0.0
  mockito_builder_annotations:
    git:
      url: https://github.com/digitalrmdy/mockito-builder.git
      path: annotations
      ref: feature/nullsafe
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  mockito_builder_annotations:
    path: annotations
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
