///the annotation to be place on your mock method.
class GenerateMocker {
  ///the types to generate Mock classes for
  final List<Type> types;

  ///types that have already been generated by mockito.
  final List<Type> mockitoGeneratedTypes;

  ///generate extensions for [mockitoGeneratedTypes] which casts it as the mock type.
  ///TODO expand on this
  ///true by default
  final bool generateMockExtensions;
  const GenerateMocker(
    this.types, {
    this.mockitoGeneratedTypes = const [],
    this.generateMockExtensions = true,
  });
}
