// Mocks generated by Mockito 5.4.1 from annotations
// in example/test/example_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import 'example_test.dart' as _i2;
import 'models/model_a.dart' as _i4;
import 'models/model_b.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ExampleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockExampleUseCase extends _i1.Mock implements _i2.ExampleUseCase {
  @override
  int exampleInt(_i2.ExampleModel? model) => (super.noSuchMethod(
        Invocation.method(
          #exampleInt,
          [model],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
}

/// A class which mocks [ExampleUseCase2].
///
/// See the documentation for Mockito's code generation for more information.
class MockExampleUseCase2 extends _i1.Mock implements _i2.ExampleUseCase2 {
  @override
  void exampleVoid() => super.noSuchMethod(
        Invocation.method(
          #exampleVoid,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Future<void> exampleFutureVoid() => (super.noSuchMethod(
        Invocation.method(
          #exampleFutureVoid,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  void operator [](String? key) => super.noSuchMethod(
        Invocation.method(
          #[],
          [key],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void operator []=(
    String? key,
    String? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #[]=,
          [
            key,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Model].
///
/// See the documentation for Mockito's code generation for more information.
class MockModelAModel extends _i1.Mock implements _i4.Model {}

/// A class which mocks [Model].
///
/// See the documentation for Mockito's code generation for more information.
class MockModelBModel extends _i1.Mock implements _i5.Model {}
