// Mocks generated by Mockito 5.0.15 from annotations
// in example/test/example_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;

import 'example_test.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ExampleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockExampleUseCase extends _i1.Mock implements _i2.ExampleUseCase {
  MockExampleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int example(int? i) =>
      (super.noSuchMethod(Invocation.method(#example, [i]), returnValue: 0)
          as int);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ExampleUseCase2].
///
/// See the documentation for Mockito's code generation for more information.
class MockExampleUseCase2 extends _i1.Mock implements _i2.ExampleUseCase2 {
  MockExampleUseCase2() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void example2() => super.noSuchMethod(Invocation.method(#example2, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ExampleUseCase4].
///
/// See the documentation for Mockito's code generation for more information.
class MockExampleUseCase4 extends _i1.Mock implements _i2.ExampleUseCase4 {
  MockExampleUseCase4() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String toString() => super.toString();
}

/// A class which mocks [ExampleUseCase5].
///
/// See the documentation for Mockito's code generation for more information.
class MockExampleUseCase5 extends _i1.Mock implements _i2.ExampleUseCase5 {
  MockExampleUseCase5() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String toString() => super.toString();
}

/// A class which mocks [ExampleUseCase6].
///
/// See the documentation for Mockito's code generation for more information.
class MockExampleUseCase6 extends _i1.Mock implements _i2.ExampleUseCase6 {
  MockExampleUseCase6() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String toString() => super.toString();
}

/// A class which mocks [ExampleUseCase7].
///
/// See the documentation for Mockito's code generation for more information.
class MockExampleUseCase7 extends _i1.Mock implements _i2.ExampleUseCase7 {
  MockExampleUseCase7() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String toString() => super.toString();
}
