// Mocks generated by Mockito 5.0.15 from annotations
// in example/test/example_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import 'example_test.dart' as _i2;
import 'models/model_a.dart' as _i4;
import 'models/model_b.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ExampleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockExampleUseCase extends _i1.Mock implements _i2.ExampleUseCase {
  @override
  int exampleInt(_i2.ExampleModel? model) => (super
          .noSuchMethod(Invocation.method(#exampleInt, [model]), returnValue: 0)
      as int);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ExampleUseCase2].
///
/// See the documentation for Mockito's code generation for more information.
class MockExampleUseCase2 extends _i1.Mock implements _i2.ExampleUseCase2 {
  @override
  void exampleVoid() => super.noSuchMethod(Invocation.method(#exampleVoid, []),
      returnValueForMissingStub: null);
  @override
  _i3.Future<void> exampleFutureVoid() =>
      (super.noSuchMethod(Invocation.method(#exampleFutureVoid, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Model].
///
/// See the documentation for Mockito's code generation for more information.
class MockModelAModel extends _i1.Mock implements _i4.Model {
  @override
  String toString() => super.toString();
}

/// A class which mocks [Model].
///
/// See the documentation for Mockito's code generation for more information.
class MockModelBModel extends _i1.Mock implements _i5.Model {
  @override
  String toString() => super.toString();
}
