// Mocks generated by Mockito 5.0.15 from annotations
// in example/test/mocker_with_custom_mockito_annotation.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;

import 'mocker_with_custom_mockito_annotation.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [MockerWithCustomMockitoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockerWithCustomMockitoUseCase extends _i1.Mock
    implements _i2.MockerWithCustomMockitoUseCase {
  MockMockerWithCustomMockitoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void test() => super.noSuchMethod(Invocation.method(#test, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [MockerWithCustomMockitoUseCase2].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockerWithCustomMockitoUseCase2 extends _i1.Mock
    implements _i2.MockerWithCustomMockitoUseCase2 {
  MockMockerWithCustomMockitoUseCase2() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void test() => super.noSuchMethod(Invocation.method(#test, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
